### PR TITLE
changes for 0.12

### PR DESCRIPTION
**Pull request by justinwoo**
should go in `compiler/0.12`

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much!

What does `"#compiler/0.12"` mean in the `bower.json` files? Do you want to refer to a specific branch? Why would we remove semantic versioning?

**Comment by justinwoo** [comment]
as in a lot of these are being collected in a "compiler/0.12" branch for the 0.12-rc1 version of the compiler, so these are just one way to be able to have mutable pre-releases. once 0.12 is released, we should be able to then have full-fledged versions published and merge these back to master and tag them

**Comment by sharkdp** [comment]
So should these changes also go into a separate branch?

(Also, is there any way to build/test the 0.12 changes with Travis?)

**Comment by justinwoo** [comment]
Yeah, into a branch called `compiler/0.12` would be best.

There's not a convenient way to build on Travis other than to install by downloading the bin and updating the path: https://github.com/purescript/package-sets/blob/949e3eb9c52be6bc9cc859ddeccca63a039c891e/.travis.yml#L14-L17

**Comment by sharkdp** [comment]
Thank you for the clarification. I have added a `compiler/0.12` branch. Could you please change the PR to target this branch?

**Comment by justinwoo** [comment]
Updated it

**Comment by sharkdp** [comment]
Thank you!

**Pull request merged**
